# Generated by Django 4.2 on 2023-06-04 11:11

import authorized.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authorized", "0002_auto_20230604_1108"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authorizedimg",
            old_name="image_name",
            new_name="person_name",
        ),
        migrations.RemoveField(
            model_name="authorizedimg",
            name="authorized_img_url",
        ),
        migrations.AddField(
            model_name="authorizedimg",
            name="authorized_img",
            field=models.ImageField(
                # default=django.utils.timezone.now,
                default=None,
                upload_to=authorized.models.get_image_path,
            ),
            preserve_default=False,
        ),
    ]
