# Generated by Django 4.2 on 2023-06-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romos', '0002_alter_romo_mac_address'),
        ('intruder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruderimg',
            name='romo_mac_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='romos.romo'),
        ),
    ]
