# Generated by Django 4.2 on 2023-06-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intruder', '0002_intruderimg_romo_mac_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intruderimg',
            old_name='romo_mac_address',
            new_name='romo_id',
        ),
    ]
