# Generated by Django 4.2 on 2023-06-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intruder", "0003_rename_romo_mac_address_intruderimg_romo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="intruderimg",
            name="intruder_label_id",
            field=models.CharField(default=None, max_length=100),
            preserve_default=True,
        ),
    ]
