# Generated by Django 4.2 on 2023-06-08 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intruder", "0007_alter_intruderimg_intruder_label_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intruderimg",
            name="intruder_label_id",
        ),
    ]
