# Generated by Django 4.2 on 2023-06-08 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("intruder", "0008_remove_intruderimg_intruder_label_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="intruderimg",
            name="intruder_label_id",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
